version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka-network
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka_broker:
     image: confluentinc/cp-kafka:latest
     container_name: kafka_broker
     hostname: kafka_broker
     depends_on:
       zookeeper:
          condition: service_healthy
     ports:
        - "9092:9092"
        - "9101:9101"
     environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_broker:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=localhost
     networks:
       - kafka-network
     healthcheck:
        test: [ "CMD", "bash", "-c", 'nc -z localhost 9092' ]
        interval: 10s
        timeout: 5s
        retries: 5

  schema_registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema_registry
    hostname: schema_registry
    depends_on:
       kafka_broker:
          condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka_broker:29092  
      - SCHEMA_REGISTRY_HOST_NAME=schema_registry
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 3 
  
  control_center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control_center
    hostname: control_center
    depends_on:
       schema_registry:
          condition: service_healthy
    ports:
      - "9021:9021"
    environment:
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka_broker:29092
      - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1 
      - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1 
      - CONTROL_CENTER_REPLICATION_FACTOR=1 
      - CONFLUENT_METRICS_TOPIC_REPLICATION=1
      - CONFLUENT_METRICS_ENABLE=false
    networks:
      - kafka-network
networks:
  kafka-network: